import { useCallback, useState } from "react";
import { useTranslation } from "react-i18next";
import { buildReport, summaryText } from "../lib/report";
import type {
  BatteryInfo,
  FullHardwareInfo,
  StorageInfo,
  Verdict,
} from "../lib/types";
import type { FraudFlag } from "../lib/useScan";

export function ReportCard({
  hardware,
  battery,
  storage,
  score,
  verdict,
  flags,
}: {
  hardware: FullHardwareInfo;
  battery: BatteryInfo | null;
  storage: StorageInfo[] | null;
  score: number;
  verdict: Verdict;
  flags: FraudFlag[];
}) {
  const { t } = useTranslation();
  const [copied, setCopied] = useState(false);
  const [generatingImage, setGeneratingImage] = useState(false);

  const report = buildReport({
    hardware,
    battery,
    storage,
    score,
    verdict,
    flags,
  });

  const onCopy = useCallback(async () => {
    const text = summaryText(report, (k) => t(k));
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      const ta = document.createElement("textarea");
      ta.value = text;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    }
  }, [report, t]);

  const onExportImage = useCallback(() => {
    setGeneratingImage(true);
    try {
      const canvas = document.createElement("canvas");
      canvas.width = 600;
      canvas.height = 700;
      const ctx = canvas.getContext("2d");
      if (!ctx) return;

      // Background Gradient
      const grad = ctx.createLinearGradient(0, 0, 0, 700);
      grad.addColorStop(0, "#0f172a");
      grad.addColorStop(1, "#1e293b");
      ctx.fillStyle = grad;
      ctx.fillRect(0, 0, 600, 700);

      // Card Header
      ctx.fillStyle = "#10b981";
      ctx.font = "bold 24px sans-serif";
      ctx.fillText("Asol Naki? — Diagnosed Report", 40, 50);

      ctx.fillStyle = "#94a3b8";
      ctx.font = "14px sans-serif";
      ctx.fillText(new Date().toLocaleDateString(), 40, 75);

      // Score Card Box
      ctx.fillStyle = "rgba(255, 255, 255, 0.05)";
      ctx.strokeStyle = "rgba(255, 255, 255, 0.1)";
      ctx.lineWidth = 1;
      ctx.beginPath();
      ctx.roundRect(40, 95, 520, 120, 16);
      ctx.fill();
      ctx.stroke();

      ctx.fillStyle = verdict === "good-buy" ? "#34d399" : verdict === "negotiate" ? "#fcd34d" : "#f87171";
      ctx.font = "bold 42px sans-serif";
      ctx.fillText(`${score.toFixed(1)} / 10`, 60, 155);

      ctx.fillStyle = "#ffffff";
      ctx.font = "bold 18px sans-serif";
      const verdictLabel = verdict === "good-buy" ? "Good Buy" : verdict === "negotiate" ? "Negotiate Price" : "Walk Away";
      ctx.fillText(verdictLabel, 60, 190);

      // Hardware Breakdown
      ctx.font = "bold 16px sans-serif";
      ctx.fillStyle = "#38bdf8";
      ctx.fillText("Hardware Summary", 40, 250);

      ctx.font = "14px sans-serif";
      ctx.fillStyle = "#e2e8f0";
      let y = 280;

      const storageStr = report.storage.reduce(
        (acc: string, d: { capacityGb?: number; smartStatus?: string }) =>
          `${acc} ${d.capacityGb ?? "?"}GB (${d.smartStatus ?? "OK"})`,
        "",
      );

      const rows: [string, string][] = [
        ["Device", report.device.hostname],
        ["CPU", report.cpu],
        ["Memory", `${Math.round(report.memoryMb / 1024)} GB`],
        ["Storage", storageStr.trim() || "N/A"],
        ["Battery Health", report.battery?.healthPercent != null ? `${report.battery.healthPercent}%` : "N/A"],
      ];

      rows.forEach(([label, val]) => {
        ctx.fillStyle = "#94a3b8";
        ctx.fillText(label, 40, y);
        ctx.fillStyle = "#ffffff";
        ctx.fillText(val, 200, y);
        y += 28;
      });

      // Flags section
      if (flags.length > 0) {
        y += 10;
        ctx.font = "bold 16px sans-serif";
        ctx.fillStyle = "#f87171";
        ctx.fillText(`Integrity Flags (${flags.length})`, 40, y);
        y += 25;

        ctx.font = "12px sans-serif";
        flags.slice(0, 3).forEach((f) => {
          ctx.fillStyle = f.severity === "critical" ? "#f87171" : "#fcd34d";
          ctx.fillText(`• [${f.severity.toUpperCase()}] ${f.check_id}`, 40, y);
          y += 20;
        });
      }

      // Footer branding
      ctx.fillStyle = "#64748b";
      ctx.font = "12px sans-serif";
      ctx.fillText("Generated by Asol Naki? — Genuine Second-Hand Diagnostic Engine", 40, 660);

      const a = document.createElement("a");
      a.download = `asol-naki-report-${report.device.hostname}.png`;
      a.href = canvas.toDataURL("image/png");
      a.click();
    } finally {
      setGeneratingImage(false);
    }
  }, [report, score, verdict, flags]);

  return (
    <div className="flex gap-2">
      <button
        type="button"
        onClick={() => void onCopy()}
        className="rounded-xl bg-white/10 px-4 py-2 text-sm font-medium text-white ring-1 ring-white/20 transition-colors hover:bg-white/15"
        data-testid="copy-report"
      >
        {copied ? t("report.copied") : t("report.copy")}
      </button>

      <button
        type="button"
        onClick={onExportImage}
        disabled={generatingImage}
        className="rounded-xl bg-emerald-500/20 px-4 py-2 text-sm font-medium text-emerald-300 ring-1 ring-emerald-500/30 transition-colors hover:bg-emerald-500/30 disabled:opacity-50"
      >
        {t("report.exportImage", "Save Image")}
      </button>
    </div>
  );
}
